-- Create registration_sessions table
CREATE TABLE IF NOT EXISTS public.registration_sessions (
    phone_number TEXT PRIMARY KEY,
    step INT NOT NULL DEFAULT 1,
    first_name TEXT,
    surname TEXT,
    shop_name TEXT,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Create shops table
CREATE TABLE IF NOT EXISTS public.shops (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    surname TEXT NOT NULL,
    shop_name TEXT NOT NULL,
    address TEXT NOT NULL,
    phone_number TEXT UNIQUE NOT NULL,
    latitude NUMERIC NOT NULL,
    longitude NUMERIC NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Add missing columns to order table
ALTER TABLE public.order 
ADD COLUMN IF NOT EXISTS notified_shops_count INT DEFAULT 0,
ADD COLUMN IF NOT EXISTS declined_shops_count INT DEFAULT 0;
